# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/about.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(375, 206)
        Dialog.setMinimumSize(QtCore.QSize(375, 206))
        Dialog.setMaximumSize(QtCore.QSize(375, 206))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/_star- (Copiar).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 150, 441, 61))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/img/blue.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 111, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/img/circle.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(130, 170, 121, 20))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(150, 30, 206, 93))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.lblWeb = QtWidgets.QLabel(self.widget)
        self.lblWeb.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.lblWeb.setObjectName("lblWeb")
        self.verticalLayout.addWidget(self.lblWeb)
        self.lblEmail = QtWidgets.QLabel(self.widget)
        self.lblEmail.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout.addWidget(self.lblEmail)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About this tool"))
        self.label_13.setText(_translate("Dialog", "All rights reserved 2015"))
        self.label_3.setText(_translate("Dialog", "Author:"))
        self.label_4.setText(_translate("Dialog", "Company:"))
        self.label_5.setText(_translate("Dialog", "WebSite:"))
        self.label_6.setText(_translate("Dialog", "Email:"))
        self.label_7.setText(_translate("Dialog", "Skype:"))
        self.label_8.setText(_translate("Dialog", "Victor H. Villalobos B."))
        self.label_9.setText(_translate("Dialog", "Firesoft.CA"))
        self.lblWeb.setText(_translate("Dialog", "www.firesoft.com.ve"))
        self.lblEmail.setText(_translate("Dialog", "vvillalobos@firesoft.com.ve"))
        self.label_12.setText(_translate("Dialog", "victorvillalobos@outlook.com"))

import main_rc
