# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 186)
        MainWindow.setMinimumSize(QtCore.QSize(417, 186))
        MainWindow.setMaximumSize(QtCore.QSize(417, 186))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/taskx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineImport = QtWidgets.QLineEdit(self.centralwidget)
        self.lineImport.setReadOnly(True)
        self.lineImport.setObjectName("lineImport")
        self.horizontalLayout.addWidget(self.lineImport)
        self.btnFindImport = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/_search- (Copiar).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFindImport.setIcon(icon1)
        self.btnFindImport.setObjectName("btnFindImport")
        self.horizontalLayout.addWidget(self.btnFindImport)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnStart = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStart.setIcon(icon2)
        self.btnStart.setIconSize(QtCore.QSize(32, 32))
        self.btnStart.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_3.addWidget(self.btnStart)
        self.btnPause = QtWidgets.QToolButton(self.centralwidget)
        self.btnPause.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/_-sign-ban- (Copiar).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPause.setIcon(icon3)
        self.btnPause.setIconSize(QtCore.QSize(32, 32))
        self.btnPause.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout_3.addWidget(self.btnPause)
        self.btnStop = QtWidgets.QToolButton(self.centralwidget)
        self.btnStop.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/_-sign-error- (Copiar).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon4)
        self.btnStop.setIconSize(QtCore.QSize(32, 32))
        self.btnStop.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 21))
        self.menubar.setObjectName("menubar")
        self.menuConfiguration = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_this = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/_star- (Copiar).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_this.setIcon(icon5)
        self.actionAbout_this.setObjectName("actionAbout_this")
        self.actionConfiguration = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/_-cogs- (Copiar).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfiguration.setIcon(icon6)
        self.actionConfiguration.setObjectName("actionConfiguration")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Log = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconos/ico/32x32/Copiar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Log.setIcon(icon7)
        self.actionOpen_Log.setObjectName("actionOpen_Log")
        self.menuConfiguration.addAction(self.actionConfiguration)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionOpen_Log)
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Companies House Web Scrapping Tool"))
        self.label.setText(_translate("MainWindow", "Company Numbers File:"))
        self.lineImport.setPlaceholderText(_translate("MainWindow", "Please set the import csv file"))
        self.btnFindImport.setText(_translate("MainWindow", "..."))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnPause.setText(_translate("MainWindow", "Pause"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration"))
        self.menuHelp.setTitle(_translate("MainWindow", "Logs"))
        self.actionAbout_this.setText(_translate("MainWindow", "&About this"))
        self.actionConfiguration.setText(_translate("MainWindow", "Configuration"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_Log.setText(_translate("MainWindow", "Open Log"))

import main_rc
